#eureka的配置

spring:
   application:
        name: registry-center
server:
   port: 9000

eureka:
   instance:
       hostname: localhost
   client:
       registerWithEureka: true
       fetchRegistry: false
       serviceUrl:
           defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
   server:
        enable-self-preservation : false            
           
# log的配置
logging:
    config : classpath:log4j2.xml  
