#eureka的配置
server:
   port: 9000

eureka:
   instance:
       hostname: registry-1
   client:
       registerWithEureka: false
       fetchRegistry: false
       serviceUrl:
           defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
